#!/bin/bash

# Ce fichier a été écrit par Mathieu Picot pour le projet studio audio LibraZiK 
# Copyright : Mathieu PICOT <picotmathieu@gmail.com> 2020-2020
# Licence : GNU-GPL-3

# This file has been written by Mathieu Picot for the LibraZiK audio studio project
# Copyright: Mathieu Picot <picotmathieu@gmail.com> 2020-2020
# License: GNU-GPL-3

release=buster
apt_dir=/etc/apt

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


all_non_free=$(grep -e ^'deb ' -e ' non-free ' $apt_dir/sources.list)


# commenter dans sources.list les lignes de dépôt que nous venons d'ajouter dans sources.list.d
# afin d'éviter les doublons.

# comment repository lines in sources.list
# that we just add in sources.list.d to prevent double entries
sed -i -e "s|^deb http://deb.debian.org/debian/ $release |#&|" \
       -e "s|^deb-src http://deb.debian.org/debian/ $release |#&|" \
       -e "s|^deb http://security.debian.org/debian-security $release/updates |#&|" \
       -e "s|^deb-src http://security.debian.org/debian-security $release/updates |#&|" \
       -e "s|^deb http://deb.debian.org/debian/ $release-updates |#&|" \
       -e "s|^deb-src http://deb.debian.org/debian/ $release-updates |#&|" \
       -e "s|^deb http://deb.debian.org/debian $release-backports |#&|" \
       -e "s|^deb-src http://deb.debian.org/debian $release-backports |#&|" \
       "$apt_dir/sources.list"

       
sources_dir="$apt_dir/sources.list.d"

# ajouter non-free aux dépôts dans les fichiers dans sources.list.d/
# si non-free était présent dans le fichier sources.list

# add non-free repos present in sources.list to files added in sources.list.d/
if echo "$all_non_free" |grep -q "deb http://deb.debian.org/debian/* $release ";then
    sed -i "/^deb http:\/\/deb.debian.org\/debian\/* $release /s/$/ non-free/" "$sources_dir/${release^}.list"
fi

if echo "$all_non_free" |grep -q "deb http://deb.debian.org/debian/* $release-backports ";then
    sed -i "/^deb http:\/\/deb.debian.org\/debian\/* $release-backports /s/$/ non-free/" "$sources_dir/${release^}-backports.list"
fi

if echo "$all_non_free" |grep -q "deb http://deb.debian.org/debian/* $release-updates ";then
    sed -i "/deb http:\/\/deb.debian.org\/debian\/* $release-updates /s/$/ non-free/" "$sources_dir/${release^}-updates.list"
fi

if echo "$all_non_free" |grep -q "deb http://security.debian.org/debian-security/* $release/updates ";then
    sed -i "/deb http:\/\/security.debian.org\/debian-security\/* $release\/updates /s/$/ non-free/" "$sources_dir/${release^}-security.list"
fi

exit 0
